/*
29/12/2018
****************************

classe ESAME -> RAPPRESENTA UNA RIGA DEL LIBRETTO

https://units.esse3.pp.cineca.it/e3rest/api/libretto-service-v1/libretti/286879/righe/
****************************
[
  {
    "aaFreqId": 2017,
    "adCod": "004GI",
    "adDes": "DIRITTO COSTITUZIONALE",
    "adsceId": 5057980,
    "annoCorso": 1,
    "chiaveADContestualizzata": {
      "aaOffId": 2017,
      "aaOrdCod": "GI01-17",
      "aaOrdDes": "GIURISPRUDENZA",
      "aaOrdId": 2017,
      "adCod": "004GI",
      "adDes": "DIRITTO COSTITUZIONALE",
      "adId": 111210,
      "afId": 236857,
      "cdsCod": "GI01",
      "cdsDes": "GIURISPRUDENZA",
      "cdsId": 10094,
      "pdsCod": "PDS0-2017",
      "pdsDes": "comune",
      "pdsId": 9999
    },
    "dataFreq": "",
    "dataScadIscr": "",
    "esito": {
      "aaSupId": 2017,
      "dataEsa": "15/06/2018 00:00:00",
      "lodeFlg": 0,
      "modValCod": {
        "value": "V"
      },
      "supEsaFlg": null,
      "tipoGiudCod": "",
      "tipoGiudDes": "",
      "voto": 30
    },
    "freqObbligFlg": null,
    "freqUffFlg": 1,
    "gruppoGiudCod": "",
    "gruppoGiudDes": "",
    "gruppoVotoId": 1,
    "gruppoVotoLodeFlg": 1,
    "gruppoVotoMaxVoto": 30,
    "gruppoVotoMinVoto": 18,
    "itmId": 3,
    "matId": 286879,
    "note": "",
    "numAppelliPrenotabili": 0,
    "numPrenotazioni": 0,
    "ord": 1,
    "peso": 12,
    "pianoId": 1,
    "ragId": null,
    "raggEsaTipo": null,
    "ricId": 0,
    "sovranFlg": 0,
    "stato": {
      "value": "S"
    },
    "statoDes": "Superata",
    "stuId": 236437,
    "superataFlg": null,
    "tipoEsaCod": "O",
    "tipoEsaDes": "Orale",
    "tipoInsCod": "OBB",
    "tipoInsDes": "Obbligatoria"
  },
  {
    "aaFreqId": 2017,
    "adCod": "079GI",
    "adDes": "ECONOMIA AZIENDALE",
    "adsceId": 5057985,
    "annoCorso": 1,
    "chiaveADContestualizzata": {
      "aaOffId": 2017,
      "aaOrdCod": "GI01-17",
      "aaOrdDes": "GIURISPRUDENZA",
      "aaOrdId": 2017,
      "adCod": "079GI",
      "adDes": "ECONOMIA AZIENDALE",
      "adId": 117741,
      "afId": 236852,
      "cdsCod": "GI01",
      "cdsDes": "GIURISPRUDENZA",
      "cdsId": 10094,
      "pdsCod": "PDS0-2017",
      "pdsDes": "comune",
      "pdsId": 9999
    },
    "dataFreq": "",
    "dataScadIscr": "",
    "esito": {
      "aaSupId": null,
      "dataEsa": "",
      "lodeFlg": 0,
      "modValCod": {
        "value": "V"
      },
      "supEsaFlg": null,
      "tipoGiudCod": "",
      "tipoGiudDes": "",
      "voto": null
    },
    "freqObbligFlg": null,
    "freqUffFlg": 1,
    "gruppoGiudCod": "",
    "gruppoGiudDes": "",
    "gruppoVotoId": 1,
    "gruppoVotoLodeFlg": 1,
    "gruppoVotoMaxVoto": 30,
    "gruppoVotoMinVoto": 18,
    "itmId": 5,
    "matId": 286879,
    "note": "",
    "numAppelliPrenotabili": 0,
    "numPrenotazioni": 0,
    "ord": 2,
    "peso": 9,
    "pianoId": 1,
    "ragId": null,
    "raggEsaTipo": null,
    "ricId": 0,
    "sovranFlg": 0,
    "stato": {
      "value": "F"
    },
    "statoDes": "Frequentata",
    "stuId": 236437,
    "superataFlg": null,
    "tipoEsaCod": "O",
    "tipoEsaDes": "Orale",
    "tipoInsCod": "OBB",
    "tipoInsDes": "Obbligatoria"
  },
  {
    "aaFreqId": 2017,
    "adCod": "015GI",
    "adDes": "FILOSOFIA DEL DIRITTO",
    "adsceId": 5057979,
    "annoCorso": 1,
    "chiaveADContestualizzata": {
      "aaOffId": 2017,
      "aaOrdCod": "GI01-17",
      "aaOrdDes": "GIURISPRUDENZA",
      "aaOrdId": 2017,
      "adCod": "015GI",
      "adDes": "FILOSOFIA DEL DIRITTO",
      "adId": 111211,
      "afId": 236856,
      "cdsCod": "GI01",
      "cdsDes": "GIURISPRUDENZA",
      "cdsId": 10094,
      "pdsCod": "PDS0-2017",
      "pdsDes": "comune",
      "pdsId": 9999
    },
    "dataFreq": "",
    "dataScadIscr": "",
    "esito": {
      "aaSupId": null,
      "dataEsa": "",
      "lodeFlg": 0,
      "modValCod": {
        "value": "V"
      },
      "supEsaFlg": null,
      "tipoGiudCod": "",
      "tipoGiudDes": "",
      "voto": null
    },
    "freqObbligFlg": null,
    "freqUffFlg": 1,
    "gruppoGiudCod": "",
    "gruppoGiudDes": "",
    "gruppoVotoId": 1,
    "gruppoVotoLodeFlg": 1,
    "gruppoVotoMaxVoto": 30,
    "gruppoVotoMinVoto": 18,
    "itmId": 2,
    "matId": 286879,
    "note": "",
    "numAppelliPrenotabili": 0,
    "numPrenotazioni": 0,
    "ord": 3,
    "peso": 9,
    "pianoId": 1,
    "ragId": null,
    "raggEsaTipo": null,
    "ricId": 0,
    "sovranFlg": 0,
    "stato": {
      "value": "F"
    },
    "statoDes": "Frequentata",
    "stuId": 236437,
    "superataFlg": null,
    "tipoEsaCod": "O",
    "tipoEsaDes": "Orale",
    "tipoInsCod": "OBB",
    "tipoInsDes": "Obbligatoria"
  },
  {
    "aaFreqId": 2017,
    "adCod": "017GI",
    "adDes": "INFORMATICA DI BASE",
    "adsceId": 5058007,
    "annoCorso": 1,
    "chiaveADContestualizzata": {
      "aaOffId": 2017,
      "aaOrdCod": "GI01-06",
      "aaOrdDes": "GIURISPRUDENZA",
      "aaOrdId": 2006,
      "adCod": "017GI",
      "adDes": "INFORMATICA DI BASE",
      "adId": 111217,
      "afId": 211788,
      "cdsCod": "GI01",
      "cdsDes": "GIURISPRUDENZA",
      "cdsId": 10094,
      "pdsCod": "PDS0-2006",
      "pdsDes": "comune",
      "pdsId": 9999
    },
    "dataFreq": "",
    "dataScadIscr": "",
    "esito": {
      "aaSupId": null,
      "dataEsa": "",
      "lodeFlg": 0,
      "modValCod": {
        "value": "G"
      },
      "supEsaFlg": null,
      "tipoGiudCod": "",
      "tipoGiudDes": "",
      "voto": null
    },
    "freqObbligFlg": null,
    "freqUffFlg": 1,
    "gruppoGiudCod": "2",
    "gruppoGiudDes": "superato/non superato",
    "gruppoVotoId": 1,
    "gruppoVotoLodeFlg": 1,
    "gruppoVotoMaxVoto": 30,
    "gruppoVotoMinVoto": 18,
    "itmId": null,
    "matId": 286879,
    "note": "",
    "numAppelliPrenotabili": 1,
    "numPrenotazioni": 0,
    "ord": 4,
    "peso": 3,
    "pianoId": null,
    "ragId": null,
    "raggEsaTipo": null,
    "ricId": 0,
    "sovranFlg": 0,
    "stato": {
      "value": "F"
    },
    "statoDes": "Frequentata",
    "stuId": 236437,
    "superataFlg": null,
    "tipoEsaCod": "S",
    "tipoEsaDes": "Scritto",
    "tipoInsCod": "OBB",
    "tipoInsDes": "Obbligatoria"
  },
  {
    "aaFreqId": 2017,
    "adCod": "018GI",
    "adDes": "ISTITUZIONI DI DIRITTO PRIVATO I",
    "adsceId": 5057983,
    "annoCorso": 1,
    "chiaveADContestualizzata": {
      "aaOffId": 2017,
      "aaOrdCod": "GI01-17",
      "aaOrdDes": "GIURISPRUDENZA",
      "aaOrdId": 2017,
      "adCod": "018GI",
      "adDes": "ISTITUZIONI DI DIRITTO PRIVATO I",
      "adId": 111218,
      "afId": 236855,
      "cdsCod": "GI01",
      "cdsDes": "GIURISPRUDENZA",
      "cdsId": 10094,
      "pdsCod": "PDS0-2017",
      "pdsDes": "comune",
      "pdsId": 9999
    },
    "dataFreq": "",
    "dataScadIscr": "",
    "esito": {
      "aaSupId": 2017,
      "dataEsa": "15/07/2018 00:00:00",
      "lodeFlg": 0,
      "modValCod": {
        "value": "V"
      },
      "supEsaFlg": null,
      "tipoGiudCod": "",
      "tipoGiudDes": "",
      "voto": 28
    },
    "freqObbligFlg": null,
    "freqUffFlg": 1,
    "gruppoGiudCod": "",
    "gruppoGiudDes": "",
    "gruppoVotoId": 1,
    "gruppoVotoLodeFlg": 1,
    "gruppoVotoMaxVoto": 30,
    "gruppoVotoMinVoto": 18,
    "itmId": 6,
    "matId": 286879,
    "note": "",
    "numAppelliPrenotabili": 0,
    "numPrenotazioni": 0,
    "ord": 5,
    "peso": 9,
    "pianoId": 1,
    "ragId": null,
    "raggEsaTipo": null,
    "ricId": 0,
    "sovranFlg": 0,
    "stato": {
      "value": "S"
    },
    "statoDes": "Superata",
    "stuId": 236437,
    "superataFlg": null,
    "tipoEsaCod": "SOC",
    "tipoEsaDes": "Scritto e Orale Congiunti",
    "tipoInsCod": "OBB",
    "tipoInsDes": "Obbligatoria"
  },
  {
    "aaFreqId": 2017,
    "adCod": "019GI",
    "adDes": "ISTITUZIONI DI DIRITTO ROMANO",
    "adsceId": 5057982,
    "annoCorso": 1,
    "chiaveADContestualizzata": {
      "aaOffId": 2017,
      "aaOrdCod": "GI01-17",
      "aaOrdDes": "GIURISPRUDENZA",
      "aaOrdId": 2017,
      "adCod": "019GI",
      "adDes": "ISTITUZIONI DI DIRITTO ROMANO",
      "adId": 111213,
      "afId": 236853,
      "cdsCod": "GI01",
      "cdsDes": "GIURISPRUDENZA",
      "cdsId": 10094,
      "pdsCod": "PDS0-2017",
      "pdsDes": "comune",
      "pdsId": 9999
    },
    "dataFreq": "",
    "dataScadIscr": "",
    "esito": {
      "aaSupId": null,
      "dataEsa": "",
      "lodeFlg": 0,
      "modValCod": {
        "value": "V"
      },
      "supEsaFlg": null,
      "tipoGiudCod": "",
      "tipoGiudDes": "",
      "voto": null
    },
    "freqObbligFlg": null,
    "freqUffFlg": 1,
    "gruppoGiudCod": "",
    "gruppoGiudDes": "",
    "gruppoVotoId": 1,
    "gruppoVotoLodeFlg": 1,
    "gruppoVotoMaxVoto": 30,
    "gruppoVotoMinVoto": 18,
    "itmId": 1,
    "matId": 286879,
    "note": "",
    "numAppelliPrenotabili": 1,
    "numPrenotazioni": 0,
    "ord": 6,
    "peso": 9,
    "pianoId": 1,
    "ragId": null,
    "raggEsaTipo": null,
    "ricId": 0,
    "sovranFlg": 0,
    "stato": {
      "value": "F"
    },
    "statoDes": "Frequentata",
    "stuId": 236437,
    "superataFlg": null,
    "tipoEsaCod": "O",
    "tipoEsaDes": "Orale",
    "tipoInsCod": "OBB",
    "tipoInsDes": "Obbligatoria"
  },
  {
    "aaFreqId": 2017,
    "adCod": "021GI",
    "adDes": "PROVA DI LINGUA INGLESE (LIV. B2)",
    "adsceId": 5057984,
    "annoCorso": 1,
    "chiaveADContestualizzata": {
      "aaOffId": 2017,
      "aaOrdCod": "GI01-17",
      "aaOrdDes": "GIURISPRUDENZA",
      "aaOrdId": 2017,
      "adCod": "021GI",
      "adDes": "PROVA DI LINGUA INGLESE (LIV. B2)",
      "adId": 111222,
      "afId": 236854,
      "cdsCod": "GI01",
      "cdsDes": "GIURISPRUDENZA",
      "cdsId": 10094,
      "pdsCod": "PDS0-2017",
      "pdsDes": "comune",
      "pdsId": 9999
    },
    "dataFreq": "",
    "dataScadIscr": "",
    "esito": {
      "aaSupId": null,
      "dataEsa": "",
      "lodeFlg": 0,
      "modValCod": {
        "value": "G"
      },
      "supEsaFlg": null,
      "tipoGiudCod": "",
      "tipoGiudDes": "",
      "voto": null
    },
    "freqObbligFlg": null,
    "freqUffFlg": 1,
    "gruppoGiudCod": "2",
    "gruppoGiudDes": "superato/non superato",
    "gruppoVotoId": 1,
    "gruppoVotoLodeFlg": 1,
    "gruppoVotoMaxVoto": 30,
    "gruppoVotoMinVoto": 18,
    "itmId": 7,
    "matId": 286879,
    "note": "",
    "numAppelliPrenotabili": 0,
    "numPrenotazioni": 0,
    "ord": 7,
    "peso": 5,
    "pianoId": 1,
    "ragId": null,
    "raggEsaTipo": null,
    "ricId": 0,
    "sovranFlg": 0,
    "stato": {
      "value": "F"
    },
    "statoDes": "Frequentata",
    "stuId": 236437,
    "superataFlg": null,
    "tipoEsaCod": "SOC",
    "tipoEsaDes": "Scritto e Orale Congiunti",
    "tipoInsCod": "OBB",
    "tipoInsDes": "Obbligatoria"
  },
  {
    "aaFreqId": 2017,
    "adCod": "078GI",
    "adDes": "STORIA DEL DIRITTO MEDIEVALE E MODERNO",
    "adsceId": 5057981,
    "annoCorso": 1,
    "chiaveADContestualizzata": {
      "aaOffId": 2017,
      "aaOrdCod": "GI01-17",
      "aaOrdDes": "GIURISPRUDENZA",
      "aaOrdId": 2017,
      "adCod": "078GI",
      "adDes": "STORIA DEL DIRITTO MEDIEVALE E MODERNO",
      "adId": 117740,
      "afId": 236851,
      "cdsCod": "GI01",
      "cdsDes": "GIURISPRUDENZA",
      "cdsId": 10094,
      "pdsCod": "PDS0-2017",
      "pdsDes": "comune",
      "pdsId": 9999
    },
    "dataFreq": "",
    "dataScadIscr": "",
    "esito": {
      "aaSupId": null,
      "dataEsa": "",
      "lodeFlg": 0,
      "modValCod": {
        "value": "V"
      },
      "supEsaFlg": null,
      "tipoGiudCod": "",
      "tipoGiudDes": "",
      "voto": null
    },
    "freqObbligFlg": null,
    "freqUffFlg": 1,
    "gruppoGiudCod": "",
    "gruppoGiudDes": "",
    "gruppoVotoId": 1,
    "gruppoVotoLodeFlg": 1,
    "gruppoVotoMaxVoto": 30,
    "gruppoVotoMinVoto": 18,
    "itmId": 4,
    "matId": 286879,
    "note": "",
    "numAppelliPrenotabili": 1,
    "numPrenotazioni": 0,
    "ord": 8,
    "peso": 9,
    "pianoId": 1,
    "ragId": null,
    "raggEsaTipo": null,
    "ricId": 0,
    "sovranFlg": 0,
    "stato": {
      "value": "F"
    },
    "statoDes": "Frequentata",
    "stuId": 236437,
    "superataFlg": null,
    "tipoEsaCod": "O",
    "tipoEsaDes": "Orale",
    "tipoInsCod": "OBB",
    "tipoInsDes": "Obbligatoria"
  }
]


*/